---
- name: Apply NetworkManager configuration
  template:
    src: dns.conf.j2
    dest: /etc/NetworkManager/conf.d/dns.conf

- name: Apply resolv.conf configuration
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf

- name: Set immutable attribute on resolv.conf
  command: chattr +i /etc/resolv.conf

- name: Restart NetworkManager
  systemd:
    name: NetworkManager
    state: restarted