# roles/dns_config/tasks/main.yml

- name: Apply NetworkManager configuration for Rocky Linux
  when: ansible_distribution == 'Rocky'
  template:
    src: dns.conf.j2
    dest: /etc/NetworkManager/conf.d/dns.conf
  notify: Restart NetworkManager Rocky

- name: Apply NetworkManager configuration for Flatcar Linux
  when: ansible_distribution == 'Flatcar Container Linux by Kinvolk'
  template:
    src: dns.conf.j2
    dest: /etc/NetworkManager/conf.d/dns.conf
  notify: Restart NetworkManager Flatcar

- name: Update resolv.conf
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf

- name: Make resolv.conf immutable
  command: chattr +i /etc/resolv.conf