# playbooks/install_python_flatcar.yml
- name: Install Docker and Python using Docker on Flatcar nodes
  hosts: flatcar_nodes
  become: true
  tasks:
    - name: Install Docker
      raw: |
        if ! command -v docker &> /dev/null; then
          curl -fsSL https://get.docker.com | sh
        fi

    - name: Start Docker service
      raw: |
        sudo systemctl enable docker
        sudo systemctl start docker

    - name: Pull Python Docker image
      raw: docker pull python:3.9-slim

    - name: Create Python3 symlink using Docker
      raw: |
        mkdir -p /opt/bin
        echo '#!/bin/sh' > /opt/bin/python3
        echo 'exec docker run --rm -v /:/host -w /host python:3.9-slim python3 "$@"' >> /opt/bin/python3
        chmod +x /opt/bin/python3
