- name: Install Python using Docker on Flatcar nodes
  hosts: flatcar_nodes
  become: true
  tasks:
    - name: Pull Python Docker image
      raw: docker pull python:3.9-slim

    - name: Create symlink for python3
      raw: |
        mkdir -p /opt/bin
        ln -s /usr/bin/docker /opt/bin/python3