# playbooks/setup_dns_flatcar.yml
- name: Configure DNS on Flatcar nodes
  hosts: flatcar_nodes
  become: true
  gather_facts: no
  tasks:
    - name: Apply NetworkManager configuration
      raw: |
        cat <<EOF > /etc/NetworkManager/conf.d/dns.conf
        [main]
        dns=none
        EOF

    - name: Update resolv.conf
      raw: |
        cat <<EOF > /etc/resolv.conf
        nameserver 10.17.3.11
        EOF

    - name: Make resolv.conf immutable
      raw: chattr +i /etc/resolv.conf

    - name: Restart NetworkManager
      raw: systemctl restart NetworkManager