# playbooks/setup_dns_rocky.yml
---
- name: Configure DNS on Rocky Linux nodes
  hosts: rocky_nodes
  become: yes
  roles:
    - dns_config
  tasks:
    - name: Debug dns_servers variable
      debug:
        var: dns_servers

- name: Configure DNS on Flatcar Linux nodes
  hosts: flatcar_nodes
  become: yes
  roles:
    - dns_config
