- name: Configure DNS on Flatcar nodes
  hosts: flatcar_nodes
  become: true
  tasks:
    - name: Apply NetworkManager configuration
      template:
        src: dns.conf.j2
        dest: /etc/NetworkManager/conf.d/dns.conf

    - name: Update resolv.conf
      template:
        src: resolv.conf.j2
        dest: /etc/resolv.conf

    - name: Make resolv.conf immutable
      command: chattr +i /etc/resolv.conf

    - name: Restart NetworkManager
      command: systemctl restart NetworkManager